[package]
name = "esp-gamepad-host"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "esp-gamepad-host"
test = false
bench = false


[dependencies]
embassy-usb-host = { git = "https://github.com/embassy-rs/embassy.git", branch = "main", default-features = false, features = [
  "log",
] }
embassy-usb-driver = "0.2.2"
embassy-sync = "0.8.0"
embassy-executor = "0.10.0"
embassy-time = "0.5.1"
esp-backtrace = { version = "0.20.0", features = ["esp32s3", "panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "0.6.0", features = ["esp32s3"] }
esp-hal = { version = "1.2.2", features = ["esp32s3", "log-04", "unstable"] }
# 只在 feature `rt-led` 打开时使用
esp-hal-smartled = { version = "0.18.0", optional = true }
smart-leds = { version = "0.4", optional = true }
esp-println = { version = "0.18.0", features = ["esp32s3", "log-04"] }
esp-rtos = { version = "0.4.0", features = ["esp32s3", "embassy", "log-04"] }
log = "0.4.34"

[features]
default = ["rt-led"]
rt-led = ["dep:esp-hal-smartled", "dep:smart-leds"]

[patch.crates-io]
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", branch = "main" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy.git", branch = "main" }
embassy-time-queue-utils = { git = "https://github.com/embassy-rs/embassy.git", branch = "main" }
embassy-executor-timer-queue = { git = "https://github.com/embassy-rs/embassy.git", branch = "main" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy.git", branch = "main" }

[profile.release]
debug = true
debug-assertions = true
lto = "fat"
codegen-units = 1
