[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor"

rustflags = ["-C", "link-arg=-Wl,-Tlinkall.x", "-C", "link-arg=-nostartfiles"]

[env]
ESP_LOG = "info"
# ESP_LOG = "embassy_usb_host=trace,info"

[unstable]
build-std = ["core", "alloc"]

[build]
target = "xtensa-esp32s3-none-elf"

